
name: deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    outputs:
      tagName: ${{ steps.set-tagName.outputs.tagName }}

    steps:
      - uses: actions/checkout@v2

      - name: Set TagName
        id: set-tagName
        run: |
          echo tagName=${$GITHUB_REF#*tags/}
          echo "::set-output name=tagName::$tagName"
      
        
