name: deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  beforeDeploy:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.set-version.outputs.version }}
      releaseNote: ${{ steps.set-releaseNote.outputs.releaseNote }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::$(node build/deploy/getVersion.js)"

      - name: Set Release Note
        id: set-releaseNote
        run: |
          echo "::set-output name=releaseNote::$(node build/deploy/change-log.js --path=examples/docs/docs/changelog.md)"
  
  deploy:
    needs: beforeDeploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Check Deploy
        run: node build/deploy/check-deploy.js
        env:
          RELEASE_NOTE: ${{ needs.beforeDeploy.outputs.releaseNote }}

      - name: Npm Publish
        run: |
          echo ${{ secrets.NPM_TOKEN }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.beforeDeploy.outputs.version }}
          release_name: ${{ needs.beforeDeploy.outputs.version }}
          body: ${{ needs.beforeDeploy.outputs.releaseNote }}
          draft: false
          prerelease: false
