
name: deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  beforeDeploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    outputs:
      version: ${{ steps.set-version.outputs.version }}
      releaseNote: ${{ steps.set-releaseNote.outputs.releaseNote }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm install

      - name: Set Version
        id: set-version
        run: |
          echo "::set-output name=version::$(node build/deploy/getVersion.js)"

      - name: Set Release Note
        id: set-releaseNote
        run: |
          echo "::set-output name=releaseNote::$(node build/deploy/change-log.js --path=examples/docs/docs/changelog.md)"
  
  deploy:
    needs: beforeDeploy

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm install

      - name: Check Deploy
        run: node build/deploy/check-deploy.js
        env:
          RELEASE_NOTE: ${{ needs.beforeDeploy.outputs.releaseNote }}

      - name: echo
        run: |
          echo "${{ needs.beforeDeploy.outputs.releaseNote }}"
          echo "${{ needs.beforeDeploy.outputs.version }}"
          echo "haha"
