
name: deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    outputs:
      ref: $GITHUB_REF
      changelog: ${{ steps.set-changelog.outputs.changelog }}

    steps:
      - uses: actions/checkout@v2

      - name: Set Changelog
        id: set-changelog
        run: |
          echo "::set-output name=changelog::$(node build/deploy/change-log.js --path=examples/docs/docs/changelog.md --version=$RELEASE_NAME)"
      
        
